(function (root, factory) {
  const value = factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = value;
  }
  root.GGRDPresaleConfig = value;
})(typeof globalThis !== 'undefined' ? globalThis : window, function () {
  return {
    presaleAddress: '0xd8983534dd3c369d85127f6C9B85d98768139387',
    defaultPayTokenAddress: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
    saleTokenAddress: '0xA0d5663d57b7D7EF975D2F02BcAEaf5c94c671f9',
    walletConnectProjectId: 'ad704bd8122e267d73cb15391aa2ae95',
    pollIntervalMs: 30000,
    stageScanLimit: 16,
    successLiquidityBps: 8000,
    successMarketingBps: 2000,
    immediateClaimBps: 5000,
    claimLinearDays: 60,
    chain: {
      id: 56,
      hexId: '0x38',
      name: 'BNB Smart Chain',
      rpcUrls: ['https://bsc-dataseed1.binance.org/'],
      blockExplorerUrls: ['https://bscscan.com/'],
      nativeCurrency: {
        name: 'BNB',
        symbol: 'BNB',
        decimals: 18,
      },
    },
    presaleAbi: [
      'function PRICE_SCALE() view returns (uint256)',
      'function PRESALE_DURATION() view returns (uint256)',
      'function CLAIM_LINEAR_DURATION() view returns (uint256)',
      'function saleToken() view returns (address)',
      'function payToken() view returns (address)',
      'function saleDecimals() view returns (uint8)',
      'function payDecimals() view returns (uint8)',
      'function liquidityWallet() view returns (address)',
      'function marketingWallet() view returns (address)',
      'function startTs() view returns (uint256)',
      'function endTs() view returns (uint256)',
      'function softcap() view returns (uint256)',
      'function hardcap() view returns (uint256)',
      'function minBuy() view returns (uint256)',
      'function globalMaxPerWallet() view returns (uint256)',
      'function tokenCap() view returns (uint256)',
      'function totalRaised() view returns (uint256)',
      'function totalSold() view returns (uint256)',
      'function finalized() view returns (bool)',
      'function succeeded() view returns (bool)',
      'function finalizedAt() view returns (uint256)',
      'function currentStageId() view returns (uint8)',
      'function stageConfig(uint8 stageId) view returns (uint256 allocation, uint256 priceScaled, uint256 walletCap, uint256 sold, uint256 raised)',
      'function quoteTokensForStage(uint8 stageId, uint256 payIn) view returns (uint256)',
      'function quoteCurrentStage(uint256 payIn) view returns (uint8 stageId, uint256 tokenOut)',
      'function contributed(address buyer) view returns (uint256)',
      'function purchased(address buyer) view returns (uint256)',
      'function claimed(address buyer) view returns (uint256)',
      'function claimable(address buyer) view returns (uint256)',
      'function stageContributed(uint8 stageId, address buyer) view returns (uint256)',
      'function buy(uint256 payIn) external',
      'error InvalidStage()',
      'error PresaleNotActive()',
      'error AlreadyFinalized()',
      'error TooEarlyToFinalize()',
      'error MinBuyNotMet()',
      'error HardcapExceeded()',
      'error StageTokenAllocationExceeded()',
      'error StageWalletCapExceeded()',
      'error GlobalWalletCapExceeded()',
      'error ZeroTokenOut()',
      'error TokenCapExceeded()',
      'error ClaimUnavailable()',
      'error NothingToClaim()',
      'error RefundUnavailable()',
      'error NothingToRefund()',
      'error SafeERC20FailedOperation(address token)',
    ],
    erc20Abi: [
      'function allowance(address owner, address spender) view returns (uint256)',
      'function approve(address spender, uint256 amount) returns (bool)',
      'function balanceOf(address owner) view returns (uint256)',
      'function decimals() view returns (uint8)',
      'function symbol() view returns (string)',
    ],
  };
});
